export default {
  GET_STARSHIP_DETAILS: "GET_STARSHIP_DETAILS",
  GET_STARSHIP_DETAILS_SUCCESS: "GET_STARSHIP_DETAILS_SUCCESS",
  GET_STARSHIP_DETAILS_ERROR: "GET_STARSHIP_DETAILS_ERROR",

  USER_SIGNUP_DETAILS_START: "USER_SIGNUP_DETAILS_START",
  USER_SIGNUP_DETAILS_SUCCESS: "USER_SIGNUP_DETAILS_SUCCESS",
  USER_SIGNUP_DETAILS_ERROR: "USER_SIGNUP_DETAILS_ERROR",

  USER_LOGIN_START:"USER_LOGIN_START",
  USER_LOGIN_SUCCESS:"USER_LOGIN_SUCCESS",
  USER_LOGIN_ERROR:"USER_LOGIN_ERROR",

  COMPANY_SIGNUP_DETAILS_START: "COMPANY_SIGNUP_DETAILS_START",
  COMPANY_SIGNUP_DETAILS_SUCCESS: "COMPANY_SIGNUP_DETAILS_SUCCESS",
  COMPANY_SIGNUP_DETAILS_ERROR: "COMPANY_SIGNUP_DETAILS_ERROR",


  GET_COMPANIES_DETAILS_START:"GET_COMPANIES_DETAILS_START",
  GET_COMPANIES_DETAILS_SUCCESS:"GET_COMPANIES_DETAILS_SUCCESS",
  GET_COMPANIES_DETAILS_ERROR:"GET_COMPANIES_DETAILS_ERROR",

  
  GET_DEPARTMENT_DETAILS_START:"GET_DEPARTMENT_DETAILS_START",
  GET_DEPARTMENT_DETAILS_SUCCESS:"GET_DEPARTMENT_DETAILS_SUCCESS",
  GET_DEPARTMENT_DETAILS_ERROR:"GET_DEPARTMENT_DETAILS_ERROR",


  FORGOT_PASSWORD_DETAILS_START:"FORGOT_PASSWORD_DETAILS_START",
  FORGOT_PASSWORD_DETAILS_SUCCESS:"FORGOT_PASSWORD_DETAILS_SUCCESS",
  FORGOT_PASSWORD_DETAILS_ERROR:"FORGOT_PASSWORD_DETAILS_ERROR",

  
 RESET_PASSWORD_DETAILS_START:"RESET_PASSWORD_DETAILS_START",
 RESET_PASSWORD_DETAILS_SUCCESS:"RESET_PASSWORD_DETAILS_SUCCESS",
 RESET_PASSWORD_DETAILS_ERROR:"RESET_PASSWORD_DETAILS_ERROR",

 UPDATE_PASSWORD_DETAILS_START:"UPDATE_PASSWORD_DETAILS_START",
 UPDATE_PASSWORD_DETAILS_SUCCESS:"UPDATE_PASSWORD_DETAILS_SUCCESS",
 UPDATE_PASSWORD_DETAILS_ERROR:"UPDATE_PASSWORD_DETAILS_ERROR",

 UPDATE_PROFILE_DETAILS_START:"UPDATE_PROFILE_DETAILS_START",
 UPDATE_PROFILE_DETAILS_SUCCESS:"UPDATE_PROFILE_DETAILS_SUCCESS",
 UPDATE_PROFILE_DETAILS_ERROR:"UPDATE_PROFILE_DETAILS_ERROR",

 EMAIL_VERIFICATION_DETAILS_START:"EMAIL_VERIFICATION_DETAILS_START",
 EMAIL_VERIFICATION_DETAILS_SUCCESS:"EMAIL_VERIFICATION_DETAILS_SUCCESS",
 EMAIL_VERIFICATION_DETAILS_ERROR:"EMAIL_VERIFICATION_DETAILS_ERROR",

    ADMIN_COMPANIES_START:" ADMIN_COMPANIES_START",
    ADMIN_COMPANIES_SUCCESS:"ADMIN_COMPANIES_SUCCESS",
    ADMIN_COMPANIES_ERROR:"ADMIN_COMPANIES_ERROR",

    ADMIN_COMPANIES_UPDATE_COMPANY_STATUS_START:"ADMIN_COMPANIES_UPDATE_COMPANY_STATUS_START",
    ADMIN_COMPANIES_UPDATE_COMPANY_STATUS_SUCCESS:"ADMIN_COMPANIES_UPDATE_COMPANY_STATUS_SUCCESS",
    ADMIN_COMPANIES_UPDATE_COMPANY_STATUS_ERROR:"ADMIN_COMPANIES_UPDATE_COMPANY_STATUS_ERROR"


};
